# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('price', models.FloatField()),
                ('reference_code', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hourly_price', models.FloatField()),
                ('lights_price', models.FloatField()),
                ('half_hour_bookings', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SportsCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, default=None, max_length=40)),
                ('website', models.CharField(blank=True, default=None, max_length=200)),
                ('description', models.TextField(blank=True, default=None, max_length=1000)),
                ('municipal', models.BooleanField(default=False)),
                ('locker_room', models.BooleanField(default=False)),
                ('lockers', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('equipment_rental', models.BooleanField(default=False)),
                ('opening_time_mon', models.TimeField(blank=True, default='00:00:00')),
                ('closing_time_mon', models.TimeField(blank=True, default='00:00:00')),
                ('opening_time_tue', models.TimeField(blank=True, default='00:00:00')),
                ('closing_time_tue', models.TimeField(blank=True, default='00:00:00')),
                ('opening_time_wed', models.TimeField(blank=True, default='00:00:00')),
                ('closing_time_wed', models.TimeField(blank=True, default='00:00:00')),
                ('opening_time_thu', models.TimeField(blank=True, default='00:00:00')),
                ('closing_time_thu', models.TimeField(blank=True, default='00:00:00')),
                ('opening_time_fri', models.TimeField(blank=True, default='00:00:00')),
                ('closing_time_fri', models.TimeField(blank=True, default='00:00:00')),
                ('opening_time_sat', models.TimeField(blank=True, default='00:00:00')),
                ('closing_time_sat', models.TimeField(blank=True, default='00:00:00')),
                ('opening_time_sun', models.TimeField(blank=True, default='00:00:00')),
                ('closing_time_sun', models.TimeField(blank=True, default='00:00:00')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Owner')),
            ],
            options={
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='SportsCenterSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SportsCenter')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sport'),
        ),
        migrations.AddField(
            model_name='court',
            name='sports_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SportsCenter'),
        ),
        migrations.AddField(
            model_name='court',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Surface'),
        ),
        migrations.AddField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Court'),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Court'),
        ),
    ]
