# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCenterMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='core/sports_centers_images/')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sports_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SportsCenter')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
