# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sportscentermedia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='sportscenter',
            old_name='city',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='sportscentermedia',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='sports_centers_images/'),
        ),
    ]
