# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170908_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscenter',
            name='private_info',
            field=models.TextField(blank=True, default=None, max_length=1000),
        ),
    ]
